name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: |
        cd ./src
        go build -o ../example/main

    - name: Run commands
      run: |
        cd ./example
        ./main --generate
        public_key=$(cat public_key.pem)
        private_key=$(cat private_key.pem)

        ./main --generate
        new_public_key=$(cat public_key.pem)
        new_private_key=$(cat private_key.pem)

        if [[ "$public_key" == "$new_public_key" || "$private_key" == "$new_private_key" ]]; then
          echo "Key generation duplication."
          exit 1
        fi
        
        ./main --sign private_key.pem file_to_sign.txt
        ./main --verify public_key.pem signature.pem file_to_sign.txt > result.log

    - name: Validate result
      run: |
        cd ./example
        output=$(cat result.log)
        if [[ "$output" != "Signature validation -> OK" ]]; then
          echo "The result did not match 'OK'"
          exit 1
        fi
        echo "The result is 'OK'."
